services:
  db-dev:
    container_name: db-dev
    build: images/db/dev
    volumes:
      - db-dev-data:/var/lib/postgresql/shared-data/
    env_file:
     - .env
    ports:
      - 5432:5432
  db-prod:
    container_name: db-prod
    build: images/db/prod
    volumes:
      - db-prod-data:/var/lib/postgresql/shared-data/
    env_file:
      - .env
    ports:
      - 5432:5432
  importer:
    container_name: importer
    build: images/python
    command: python3 main.py
    volumes:
      - ./src/importer:/usr/src/app
      - ./volumes/csv:/csv
    env_file:
      - .env
    depends_on:
      - db-dev
volumes:
  db-dev-data:
  db-prod-data:
